### ISSUE TITLE
Internal query keyboard

### ISSUE THREAD

**Issue by PoMaKoM** [grammyjs/stateless-question#26]
I want to be able to pass the [Custom Keyboard](https://grammy.dev/plugins/keyboard.html#custom-keyboards) to the StatelessQuestio.replyWith...

**Comment by EdJoPaTo** [comment]
This is not possible with the current state of the Telegram API. See #1 or [this section in the README](https://github.com/grammyjs/stateless-question#sending-an-abortback-inline-button-with-the-question-message) for more details.

 But it would be nice! Sadly I have no idea how to get Telegram to implement that…
