### ISSUE TITLE
Question deleting keyboard when answering user

### ISSUE THREAD

**Issue by Satont** [grammyjs/stateless-question#28]
When you make call of `question.replyWithMarkdown`, but in chat you also have `Keyboard`, then keyboard disapearing.

**Comment by EdJoPaTo** [comment]
This is the same problem as #1 as there can only be one `markup_reply` at a time so either a Keyboard or ForceReply. I would really like to have support for that too…

**Comment by Satont** [comment]
Ok, thank you. Then I'll use router for such case.

**Comment by EdJoPaTo** [comment]
If you have a workaround for that feel free to share as #1 clearly has a lot of interest by different people.
