### ISSUE TITLE
session in questions not work

### ISSUE THREAD

**Issue by Hosexn** [grammyjs/stateless-question#32]
hi
i want use sessions to store data
```
export const addWalletQuestion = new StatelessQuestion<MyContext>('wallets', async (ctx, additionalState) => {
	ctx.session.data.wallets.push({name:ctx.message.text})
	await addWalletAddressQuestion.replyWithMarkdown(ctx, 'address of wallet?', 'address');
})
```
bot session in ctx not defined
how can solve this problem?
thanks

**Comment by EdJoPaTo** [comment]
Is this a TypeScript issue or a runtime issue? If TypeScript does not have the ctx.session then your `MyContext` is missing the session information. If ctx.session is undefined on runtime then your session middleware needs to be imported first before the question middleware.

Does that already help?

**Comment by EdJoPaTo** [comment]
I think the issue can be closed then? If not feel free to answer and reopen!
